/*
*	Program To check number is anagram or not
*	Anagram Numbers :An anagram number is a number that can be 
*   multiplied by at least one single digit number (other than 1) to
*	become *anagram of itself. Any anagrams formed by multiplying 
*	an anagram number by a digit are said to be generated by that 
*	anagram number. 
*	Two numbers are anagrams of each other if they can both be formed by 
*	rearranging the same combination of digits.
*/
#include<stdio.h>

void isAnagram(long);

int main()
{
	long lNum = 0;
	printf("Enter the number\n");
	scanf("%ld", &lNum);
	isAnagram(lNum);
	return 0;
}
////////////////////////////////////////////////////////////////
//
//	Name		:isAnagram
//	Input		:long
//	Returns		:void
//	Description	:Checks whether number is Anagram number or not
//	Author		:Pranav Choudhary
//	Date		:3 August 2020
//
////////////////////////////////////////////////////////////////
void isAnagram(
               		long lNum
               )
{
	int iArr[10], i = 0, k = 0;
	long lTemp1 = lNum, lTemp2 = 0L;
	if(lNum == 0)
		return;

	lNum = (lNum < 0) ? -lNum : lNum;

	i = 2;
	do
	{
		for(k = 0; k < 10; k++)
		{	
			iArr[k] = 0;
		}
		lTemp1 = lNum;
		lTemp2 = lNum * i;
		while(lTemp2 != 0 && lTemp1 != 0)
		{
			iArr[lTemp1 % 10]++;
			iArr[lTemp2 % 10]--;
			lTemp1 = lTemp1 / 10;
			lTemp2 = lTemp2 / 10;
		}
		if(lTemp1 != 0 || lTemp2 != 0)
		{
			printf("No Anagram number\n");
			return;
		}
		for(k = 0; k < 10; k++)
		{
			if(iArr[k] != 0)
				break;
		}
		if(k == 10)
		{
			printf("\n%ld is Anagram by multiplying %d \n",lNum, i);
		}
		i++;
	}while(i != lNum);
}