/*
*	Program To check number is anagram or not
*	Anagram Numbers :An anagram number is a number that can be 
*   multiplied by at least one single digit number (other than 1) to
*	become *anagram of itself. Any anagrams formed by multiplying 
*	an anagram number by a digit are said to be generated by that 
*	anagram number. 
*	Two numbers are anagrams of each other if they can both be formed by 
*	rearranging the same combination of digits.
*/
#include<stdio.h>
#define TRUE	1
#define FALSE	0
#define ERR		-1
typedef char BOOL;

BOOL isAnagram(unsigned long, unsigned long);

int main()
{
	unsigned long lNum1 = 0, lNum2 = 0;
	BOOL bRet = FALSE; 
	printf("Enter the number1\n");
	scanf("%lu", &lNum1);
	printf("Enter the number2\n");
	scanf("%lu", &lNum2);
	printf("sizeof lNum = %d \n", sizeof(lNum1));
	bRet = isAnagram(lNum1, lNum2);
	if(bRet == TRUE)
		printf("Two numbers are anagram\n");
	else
		printf("Two numbers are not anagram\n");
	return 0;
}
////////////////////////////////////////////////////////////////
//
//	Name		:isAnagram
//	Input		:unsigned long, unsigned long
//	Returns		:BOOL
//	Description	:Checks 2 numbers are Anagram number or not
//	Author		:Pranav Choudhary
//	Date		:3 August 2020
//
////////////////////////////////////////////////////////////////
BOOL isAnagram(
               		unsigned long lNum1,
               		unsigned long lNum2
               )
{
	int iArr[10], i = 0;
	if(lNum1 == 0 || lNum2 == 0)
		return ERR;
	for(i = 0; i < 10; i++)
	{	
		iArr[i] = 0;
	}	
	while(lNum2 != 0 && lNum1 != 0)
	{
		iArr[lNum1 % 10]++;
		iArr[lNum2 % 10]--;
		lNum1 = lNum1 / 10;
		lNum2 = lNum2 / 10;
	}
	if(lNum1 != 0 || lNum2 != 0)
	{
		return FALSE;
	}
	for(i = 0; i < 10; i++)
	{
		if(iArr[i] != 0)
			break;
	}
	if(i == 10)
		return TRUE;
	else
		 return FALSE;

}